### PR TITLE
Includes custom image display for characters

### PR DESCRIPTION
**Pull request by Lypsilonx**
Just put your images to server/images/<id>.png and they will be displayed instead of the name of the character

### CODE REVIEW

**Comment by Berny23** [comment]
Thanks for your contribution!

**Comment by Luigimeansme** [comment]
Ok, I'm testing this out now but it doesn't appear to be working? I got an image for Batman, named it Batman.png, and placed it in server/images both with and without a folder called .png, but no image is showing. What exactly am I doing wrong @Lypsilonx?

**Comment by Lypsilonx** [comment]
they need to be named after the ids (because names could technically be ambiguous) so it should be called 1.png (in the case of batman)

**Comment by Luigimeansme** [comment]
> they need to be named after the ids (because names could technically be ambiguous) so it should be called 1.png (in the case of batman)

I tried that as well, as well as having another thing in there for Gandalf named 2.png and it doesn't show up either

**Comment by Lypsilonx** [comment]
You can find all the ids [here](https://github.com/Berny23/LD-ToyPad-Emulator/blob/master/server/json/charactermap.json)

**Comment by Lypsilonx** [comment]
thats wierd... its working on my end, so could you maybe send the error in the console or the html (inspect the figure)

**Comment by Luigimeansme** [comment]
image
image

You can see my FTP program here where you see the folders and the files I placed in them

**Comment by Lypsilonx** [comment]
ah... I think you placed the files in another folder called ".png" you dont need that
It might have been an issue with my initial message, where github deleted the "id" in angle brackets

**Comment by Luigimeansme** [comment]
image

I tried this too, still nothing. Using inspect on the webpage shows the following error

image

**Comment by Lypsilonx** [comment]
I have made another pull request that might fix the issue, but if that doesn't work I'm afraid it might take me a while to fix it

**Comment by Lypsilonx** [comment]
What is the url you are connecting to exactly? That might help to...

**Comment by Luigimeansme** [comment]
I'm just connecting to the Pi's IP address, you can see it in that image with the 404 error code

**Comment by Luigimeansme** [comment]
image
Haha! Gottem! Good job on the fix @Lypsilonx! I'm gonna delete the image that shows my Pi's IP now, I don't feel comfortable with that being permanently on the internet

**Pull request merged**
