### PR TITLE
added pad color filter prototype

### PR DESCRIPTION
**Pull request by pablo5425**
index.js modified to include a switch that changes colors being generated so they display more accurately
also index.html has been modified to change initial pad colors so it looks like the pad is turned off until its connected to the game

this commit might say that files content was completely replaced but this is just a strange side effect from testing them in the virtual machine

### CODE REVIEW

**Comment by Berny23** [comment]
Your files have a line feed mismatch (CRLF, but should be LF).

**Comment by Berny23** [comment]
I fixed the line feed issue, thanks for your contribution! 👍

**Comment by Luigimeansme** [comment]
I just ran a test on the Portal level to test out the five main keystones, and it all seems to look great! The only problem I really noticed was the orange side of Scale being dark a lot longer than it should've according to the onscreen toypad, but I don't know if that's the game sending weird info to the toypad or if it has something to do with this change, just thought it was worth mentioning

**Comment by pablo5425** [comment]
> I just ran a test on the Portal level to test out the five main keystones, and it all seems to look great! The only problem I really noticed was the orange side of Scale being dark a lot longer than it should've according to the onscreen toypad, but I don't know if that's the game sending weird info to the toypad or if it has something to do with this change, just thought it was worth mentioning

i had some issues with that part of the code. mostly bc i was missing some breaks
just made a small check and it can be fixed by deleting the 80 in "#ff1e0080"
i dont understand why central pad starts off tho. it needs a blink animation to turn white

**Comment by pablo5425** [comment]
sent pull request #151 with fixed orange for scale keystone

**Comment by cort1237** [comment]
> i dont understand why central pad starts off tho. it needs a blink animation to turn white

I can offer a little insight. Basically the game doesn't just send straight hex values it also specifies a type of function. IIRC it's COL (Set Color), FLSH (Flash Color), FADE (Fade Color). At the moment only COL functions work, bc I didn't have working hardware with me to see exactly how to should look. You can see listeners for the unimplemented functions in index.js and see what data is being received if you wanna give a crack at it.

**Pull request merged**
